image: docker:stable
services:
  - docker:stable-dind

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

deploy-production:
  image: linuxbrew/debian:latest
  stage: deploy
  before_script:
    - brew install kubectl
    - brew install doctl
    - brew install helm@3
    - helm version
    - doctl auth init -t $DIGITAL_OCEAN_TOKEN
    - doctl kubernetes cluster kubeconfig save $DIGITAL_OCEAN_KUBERNETES_NAME
  script:
    - helm lint ./k8s/tubecentric --strict
    - helm repo add stable https://kubernetes-charts.storage.googleapis.com
    - helm repo update
    - helm upgrade --install --namespace kube-system --set rbac.enabled=true --set ssl.enabled=true --set ssl.enforced=true --set acme.enabled=true --set acme.email=dev.tubecentric@gmail.com --set acme.staging=false --set acme.challengeType=tls-alpn-01 --set acme.persistence.enabled=false traefik stable/traefik
    - helm upgrade --install --set image.tag=$CI_COMMIT_SHORT_SHA --wait --force tubecentric ./k8s/tubecentric
  when: manual
  only:
    - master