image: docker:stable
services:
  - docker:stable-dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: local

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

deploy-production:
  image: linuxbrew/debian:latest
  stage: deploy
  before_script:
    - brew install kubectl
    - brew install doctl
    - brew install kubernetes-helm
    - doctl auth init -t $DIGITAL_OCEAN_TOKEN
    - doctl kubernetes cluster kubeconfig save $DIGITAL_OCEAN_KUBERNETES_NAME
  script:
    - helm upgrade --install --set image.tag=$CI_COMMIT_SHORT_SHA --wait --force tubecentric ./k8s/tubecentric
  when: manual
  only:
    - master