image: docker:stable
services:
  - docker:stable-dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: local

stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-8
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.war

docker-build:
  stage: package
  script:
    - docker build . -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

deply-production:
  stage: deploy
  image: linkyard/docker-helm
  script:
    - helm init --upgrade
    - helm upgrade --install tubecentric --namespace default --wait --set image.tag=$CI_COMMIT_SHORT_SHA k8s/tubecentric/
  environment: 
    name: production
  when: manual
  only:
    - master