version: '3.7'

services:
  mssql:
    container_name: mssql
    image: microsoft/mssql-server-linux:latest
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - ./docker/db-init-scripts:/startup-script
    networks:
      - default
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password1!
    command: sh -c '/startup-script/mssql_entrypoint.sh & /opt/mssql/bin/sqlservr;'

  tc_web_app:
    container_name: tc_web_app
    build:
      dockerfile: DockerFile.local
      context: .
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      spring.profiles.active: "local"

networks:
  default:
    driver: bridge